name: Sanu First GitHub Action

on:
  push:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Welcome Message
        run: echo "Hello Sanu! Your first GitHub Action is running successfully!"

      - name: Show Date
        run: date

      - name: Show Current Directory
        run: pwd